List<String> areasOfPakistan = [
'Gulshan-e-Iqbal, Karachi',
'DHA Phase 6, Karachi',
'Bahria Town, Karachi',
'Clifton, Karachi',
'PECHS, Karachi',
'Korangi, Karachi',
'Nazimabad, Karachi',
'North Nazimabad, Karachi',
'Malir, Karachi',
'Orangi Town, Karachi',
'Gulistan-e-Jauhar, Karachi',
'F.B Area, Karachi',
'Liaquatabad, Karachi',
'Saddar, Karachi',
'Shah Faisal Town, Karachi',
'Site Area, Karachi',
'Garden Town, Lahore',
'Shadman, Lahore',
'Johar Town, Lahore',
'Wapda Town, Lahore',
'Model Town, Lahore',
'Iqbal Town, Lahore',
'Faisal Town, Lahore',
'Gulberg, Lahore',
'DHA Phase 1, Lahore',
'DHA Phase 2, Lahore',
'DHA Phase 3, Lahore',
'DHA Phase 4, Lahore',
'DHA Phase 5, Lahore',
'DHA Phase 7, Lahore',
'DHA Phase 8, Lahore',
'Eden Gardens, Lahore',
'PCSIR Society, Lahore',
'Askari 10, Lahore',
'Cantt, Lahore',
'Walton Road, Lahore',
'Bahria Orchard, Lahore',
'Green Town, Lahore',
'Township, Lahore',
'Samanabad, Lahore',
'Garhi Shahu, Lahore',
'Mughalpura, Lahore',
'Harbanspura, Lahore',
'Ravi Road, Lahore',
'Shahdara, Lahore',
'Badami Bagh, Lahore',
'Nishtar Colony, Lahore',
'Mehmood Booti, Lahore',
'Qila Lachman Singh, Lahore',
'Sanda, Lahore',
'Babu Sabu, Lahore',
'Kahna, Lahore',
'Ferozepur Road, Lahore',
'Multan Road, Lahore',
'Jail Road, Lahore',
'Gulshan-e-Ravi, Lahore',
'Shah Jamal, Lahore',
'Gulshan-e-Maymar, Karachi',
'PIB Colony, Karachi',
'Nagin Chowrangi, Karachi',
'Surjani Town, Karachi',
'Gizri, Karachi',
'Mehmoodabad, Karachi',
'Azizabad, Karachi',
'Buffer Zone, Karachi',
'Landhi, Karachi',
'Shershah, Karachi',
'M.A. Jinnah Road, Karachi',
'Baldia Town, Karachi',
'Tariq Road, Karachi',
'University Road, Karachi',
'Allama Iqbal Town, Lahore',
'Samnabad Town, Lahore',
'Badami Bagh, Lahore',
'Mozang, Lahore',
'New Muslim Town, Lahore',
'Old Muslim Town, Lahore',
'Kot Lakhpat, Lahore',
'Mughalpura, Lahore',
'Gulshan Ravi, Lahore',
'Garden Town, Lahore',
'Shalimar Town, Lahore',
'Sabzazar, Lahore',
'Awan Town, Lahore',
'Ali Town, Lahore',
'Shadbagh, Lahore',
'Walled City, Lahore',
'Model Town Link Road, Lahore',
'Bahria Enclave, Islamabad',
'G-5, Islamabad',
'G-6, Islamabad',
'G-7, Islamabad',
'G-8, Islamabad',
'G-9, Islamabad',
'G-10, Islamabad',
'G-11, Islamabad',
'G-12, Islamabad',
'G-13, Islamabad',
'G-14, Islamabad',
'G-15, Islamabad',
'F-5, Islamabad',
'F-6, Islamabad',
'F-7, Islamabad',
'F-8, Islamabad',
'F-10, Islamabad',
'F-11, Islamabad',
'F-12, Islamabad',
'F-13, Islamabad',
'F-14, Islamabad',
'F-15, Islamabad',
'E-7, Islamabad',
'E-8, Islamabad',
'E-9, Islamabad',
'E-10, Islamabad',
'E-11, Islamabad',
'H-8, Islamabad',
'H-9, Islamabad',
'H-10, Islamabad',
'H-11, Islamabad',
'I-8, Islamabad',
'I-9, Islamabad',
'I-10, Islamabad',
'I-11, Islamabad',
'I-12, Islamabad',
'I-13, Islamabad',
'I-14, Islamabad',
'I-15, Islamabad',
'Blue Area, Islamabad',
'Diplomatic Enclave, Islamabad',
'Bani Gala, Islamabad',
'Bhara Kahu, Islamabad',
'Chak Shahzad, Islamabad',
'Gulzar-e-Quaid, Rawalpindi',
'Saddar, Rawalpindi',
'Lalkurti, Rawalpindi',
'Chaklala, Rawalpindi',
'Tench Bhatta, Rawalpindi',
'Peshawar Road, Rawalpindi',
'Satellite Town, Rawalpindi',
'Dhoke Ratta, Rawalpindi',
'Asghar Mall Road, Rawalpindi',
'Dheri Hassanabad, Rawalpindi',
'Khanna Pul, Islamabad',
'Ghauri Town, Islamabad',
'Shamsabad, Rawalpindi',
'Murree Road, Rawalpindi',
'Airport Housing Society, Rawalpindi',
'Shaheen Town, Rawalpindi',
'PWD Housing Society, Islamabad',
'Media Town, Islamabad',
'Korang Town, Islamabad',
'Pakistan Town, Islamabad',
'Soan Gardens, Islamabad',
'DHA Phase 1, Rawalpindi',
'DHA Phase 2, Rawalpindi',
'DHA Phase 3',
  'Canal Bank Housing Scheme, Mughalpura, Lahore',
  'Al Rehman Garden, Lahore',
  'Bahria Town, Lahore',
  'Bahria Orchard, Lahore',
  'DHA Phase 6, Lahore',
  'DHA Phase 7, Lahore',
  'Lake City, Lahore',
  'Valencia Town, Lahore',
  'Model Town, Lahore',
  'PCSIR Housing Society, Lahore',
  'Wapda Town, Lahore',
  'Eden Gardens, Lahore',
  'Izmir Town, Lahore',
  'Sukh Chayn Gardens, Lahore',
  'Dream Gardens, Lahore',
  'Formanites Housing Scheme, Lahore',
  'Gulshan-e-Lahore, Lahore',
  'Green City, Lahore',
  'Iqbal Avenue Cooperative Housing Society, Lahore',
  'Jubilee Town, Lahore',
  'Punjab Government Servant Housing Scheme, Lahore',
  'Pak Arab Housing Society, Lahore',
  'Canal View, Lahore',
  'Park View Villas, Lahore',
  'LDA Avenue, Lahore',
  'Aabpara Housing Society, Lahore',
  'Architects Engineers Housing Society, Lahore',
  'NFC Phase 1, Lahore',
  'NFC Phase 2, Lahore',
  'New Lahore City, Lahore',
  'Al Kabir Town, Lahore',
  'Al Haram Garden, Lahore',
  'Al Noor Orchard, Lahore',
  'Aitchison Society, Lahore',
  'Airline Housing Society, Lahore',
  'Ali Town, Lahore',
  'Bahria Nasheman, Lahore',
  'Al Raheem Garden, Lahore',
  'Al Wahid Garden, Lahore',
  'Fazaia Housing Scheme, Lahore',
  'PGECHS Phase 1, Lahore',
  'PGECHS Phase 2, Lahore',
  'Shadman Enclave, Lahore',
  'Sui Gas Society Phase 1, Lahore',
  'Sui Gas Society Phase 2, Lahore',
  'DHA Phase 1, Karachi',
  'DHA Phase 2, Karachi',
  'DHA Phase 3, Karachi',
  'DHA Phase 4, Karachi',
  'DHA Phase 5, Karachi',
  'DHA Phase 6, Karachi',
  'DHA Phase 7, Karachi',
  'DHA Phase 8, Karachi',
  'Bahria Town Karachi, Karachi',
  'Gulshan-e-Maymar, Karachi',
  'Saadi Town, Karachi',
  'Gulshan-e-Iqbal, Karachi',
  'PECHS, Karachi',
  'Federal B Area, Karachi',
  'North Nazimabad, Karachi',
  'Clifton, Karachi',
  'Korangi, Karachi',
  'Malir Cantt, Karachi',
  'Scheme 33, Karachi',
  'Shah Faisal Town, Karachi',
  'Garden East, Karachi',
  'Garden West, Karachi',
  'Ancholi Cooperative Housing Society, Karachi',
  'Askari 4, Karachi',
  'Askari 5, Karachi',
  'Gulistan-e-Jauhar, Karachi',
  'Johar Town, Faisalabad',
  'Green Town, Faisalabad',
  'Citi Housing, Faisalabad',
  'Wapda City, Faisalabad',
  'FDA City, Faisalabad',
  'Model City, Faisalabad',
  'Eden Valley, Faisalabad',
  'Canal Garden, Faisalabad',
  'Sargodha Road, Faisalabad',
  'Millat Town, Faisalabad',
  'Madina Town, Faisalabad',
  'Sitara Valley, Faisalabad',
  'DHA Phase 1, Islamabad',
  'DHA Phase 2, Islamabad',
  'DHA Phase 3, Islamabad',
  'Bahria Town Phase 1, Islamabad',
  'Bahria Town Phase 2, Islamabad',
  'Bahria Town Phase 3, Islamabad',
  'Bahria Town Phase 4, Islamabad',
  'Bahria Town Phase 5, Islamabad',
  'Bahria Town Phase 6, Islamabad',
  'Bahria Town Phase 7, Islamabad',
  'Bahria Town Phase 8, Islamabad',
  'Gulberg Greens, Islamabad',
  'Fazaia Housing Scheme, Islamabad',
  'Multi Gardens B-17, Islamabad',
  'Gulshan-e-Sehat, Islamabad',
  'National Police Foundation, Islamabad',
  'PWD Housing Scheme, Islamabad',
  'Media Town, Islamabad',
  'Korangi Town, Karachi',
  'F-10 Markaz, Islamabad',
  'F-11 Markaz, Islamabad',
  'G-13 Markaz, Islamabad',
  'G-14 Markaz, Islamabad',
  'E-11/4, Islamabad',
  'D-12/4, Islamabad',
  'I-8/4, Islamabad',
  'I-9/4, Islamabad',
  'I-10/4, Islamabad',
  'I-11/4, Islamabad',
  'I-12/4, Islamabad',
  'Jinnah Gardens, Islamabad',
  'Soan Gardens, Islamabad',
  'Pakistan Town, Islamabad',
  'Chaklala Scheme 3, Rawalpindi',
  'Askari 14, Rawalpindi',
  'Askari 10, Rawalpindi',
  'Bahria Phase 1-6, Rawalpindi',
  'Bahria Phase 7-8, Rawalpindi',
  'Gulshan-e-Iqbal, Rawalpindi',
  'DHA Phase 1, Rawalpindi',
  'DHA Phase 2, Rawalpindi',
  'Top City-1, Islamabad',
  'Park View City, Islamabad',
  'PECHS, Islamabad',
  'Eighteen Islamabad, Islamabad',
  'Capital Smart City, Islamabad',
  'Blue World City, Islamabad',
  'University Town, Islamabad',
  'Al Ghani Garden, Lahore',
  'Pak View City, Islamabad',
  'Nova City, Islamabad',
  'Kingdom Valley, Islamabad',
  'Mumtaz City, Islamabad',
  'Gulberg Residencia, Islamabad',
  'Faisal Hills, Islamabad',
  'MPCHS, Islamabad',
  'Pine City, Murree',
  'Faisal Town, Islamabad',
  'Taj Residencia, Islamabad',
  'G-15, Islamabad',
  'B-17, Islamabad',
  'CDECHS, Islamabad',
  'Wapda Town, Islamabad',
  'Kashmir Model Town, Rawalakot',
  'Al-Haram City, Rawalpindi',
  'Airport Housing Society, Rawalpindi',
  'Ghauri Town, Islamabad',
  'Defence Garden, Karachi',
  'ASF Housing Scheme, Karachi',
  'Azizabad, Karachi',
  'Bagh-e-Korangi, Karachi',
  'Navy Housing Scheme, Karachi',
  'PECHS, Karachi',
  'Falcon Complex, Karachi',
  'Pir Gul Hassan Town, Karachi',
  'Haroon Bahria Society, Karachi',
  'DHA City, Karachi',
  'Arisha Cooperative Housing Society, Karachi',
  'Karachi University Housing Society, Karachi',
  'Karimabad Housing Society, Karachi',
  'Karim Housing Society, Karachi',
  'Gulshan-e-Maymar, Karachi',
  'Gulshan-e-Roomi, Karachi',
  'Garden City, Karachi',
  'Gulshan-e-Kaneez Fatima, Karachi',
  'Fazaia Housing Scheme, Karachi',
  'Naval Housing Scheme, Karachi',
  'Central Information Cooperative Housing Society, Karachi',
  'Behria Paradise, Karachi',
  'Palm City, Gwadar',
  'Gwadar Golf City, Gwadar',
  'New Town Housing Scheme, Gwadar',
  'China Pak Golf Estates, Gwadar',
  'Green Palms, Gwadar',
  'GDA Housing Scheme, Gwadar',
  'Gwadar Central, Gwadar',
  'Gwadar Marine Drive, Gwadar',
  'Sangar Housing Scheme, Gwadar',
  'Al Ghafoor Green City, Karachi',
  'Gulistan-e-Johar Block 15, Karachi',
  'Pakland Housing Society, Karachi',
  'North Town Residency, Karachi',
  'Malir Development Authority, Karachi',
  'Gulshan-e-Hadeed, Karachi',
  'Gulshan-e-Falaknaz, Karachi',
  'Maymar Avenue, Karachi',
  'Falaknaz Dreams, Karachi',
  'Fatima Golf Residency, Karachi',
  'Commander City, Karachi',
  'Al-Ghafoor Green City, Karachi',
  'Fazaia Bungalows, Karachi',
  'City Housing Scheme, Gujranwala',
  'Master City, Gujranwala',
  'DC Colony, Gujranwala',
  'Wapda Town, Gujranwala',
  'Fazaia Housing Scheme, Gujranwala',
  'Citi Housing, Sialkot',
  'Royal Gardens, Sialkot',
  'Khayaban-e-Nawab, Sialkot',
  'Eden Valley, Faisalabad',
  'Model City 1, Faisalabad',
  'Model City 2, Faisalabad',
  'Sitara Valley, Faisalabad',
  'Millat Town, Faisalabad',
  'Gulshan-e-Hayat, Faisalabad',
  'Motorway City, Faisalabad',
  'Zainab Garden, Faisalabad',
  'Eden Garden, Faisalabad',
  'Amin Town, Faisalabad',
  'Nisar Colony, Faisalabad',
  'Raza Garden, Faisalabad',
  'Zee Garden, Faisalabad',
  'Faisalabad Housing Scheme, Faisalabad',
  'Rachna Town, Faisalabad',
  'New Garden Town, Faisalabad',
  'Hassan Villas, Faisalabad',
  'Sargodha Road, Faisalabad',
  'Samanabad Town, Faisalabad',
  'Kohinoor City, Faisalabad',
  'Sahil Homes, Faisalabad',
  'Prime City, Faisalabad',
  'Satiana Road, Faisalabad',
  'Jinnah Colony, Faisalabad',
  'Bakar Mandi, Faisalabad',
  'Ghulam Muhammadabad, Faisalabad',
  'Sheikh Colony, Faisalabad',
  'Saeed Colony, Faisalabad',
  'Abdullah Garden, Faisalabad',
  'Model Town, Faisalabad',
  'Nisar Colony, Faisalabad',
  'Jinnah Colony, Faisalabad',
  'Khayaban-e-Manzoor, Faisalabad',
  'Makkah Garden, Faisalabad',
  'Niamuana, Faisalabad',
  'Bismillah Garden, Faisalabad',
  'Ali Housing Colony, Faisalabad',
  'Tariqabad, Faisalabad',
  'Nishatabad, Faisalabad',
  'Abdullahpur, Faisalabad',
  'Malikpur, Faisalabad',
  'Chiniot Bazar, Faisalabad',
  'People’s Colony, Faisalabad',
  'Kashmir Road, Faisalabad',
  'Saddar Bazar, Faisalabad',
  'Model Town, Faisalabad',
  'Gulberg, Faisalabad',
  'Clock Tower, Faisalabad',
  'D Ground, Faisalabad',
  'Railway Colony, Faisalabad',
  'Madina Town, Faisalabad',
  'Ismail Road, Faisalabad',
  'DHA Phase 1, Peshawar',
  'DHA Phase 2, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
  'Saddar Bazar, Peshawar',
  'Gulberg, Peshawar',
  'Bara Road, Peshawar',
  'Peshawar Road, Peshawar',
  'University Road, Peshawar',
  'Bara Road, Peshawar',
  'Hayatabad Phase 1, Peshawar',
  'Hayatabad Phase 2, Peshawar',
  'Hayatabad Phase 3, Peshawar',
  'Hayatabad Phase 4, Peshawar',
  'Hayatabad Phase 5, Peshawar',
  'Hayatabad Phase 6, Peshawar',
  'Hayatabad Phase 7, Peshawar',
  'Hayatabad Phase 8, Peshawar',
  'Hayatabad Phase 9, Peshawar',
  'Hayatabad Phase 10, Peshawar',
  'Wapda Town, Peshawar',
  'Regi Model Town, Peshawar',
  'Kohat Road, Peshawar',
  'PDA Housing Scheme, Peshawar',
  'KDA Kohat, Peshawar',
  'Kohat Enclave, Peshawar',
  'Kohat Development Authority, Peshawar',
  'Sheikh Maltoon Town, Mardan',
  'Model Town, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Mardan Enclave, Mardan',
  'Mardan Valley, Mardan',
  'Sheikh Maltoon Town, Mardan',
  'Royal Residencia, Mardan',
  'Model City, Mardan',
  'Green City, Mardan',
  'City Housing, Mardan',
  'University Town, Peshawar',
  'Shahi Bagh, Peshawar',
  'Jinnah Park, Peshawar',
  'Abdul Wali Khan University, Mardan',
  'Green Enclave, Peshawar',
  'Model Colony, Peshawar',
  'Gulshan-e-Rehman, Peshawar',
  'Hayatabad Industrial Estate, Peshawar',
  'University Town, Peshawar',
  'Tehkal Bala, Peshawar',
  'Wazir Bagh, Peshawar',
  'Karkhano Market, Peshawar',
  'Warsak Road, Peshawar',
  'Peshawar Cantonment, Peshawar',
];
